-- Clario Reference Library — Supabase Migration
-- Run in Supabase Dashboard → SQL Editor
-- Prerequisites: pgvector extension must be enabled (Supabase enables it by default on Pro plans)
-- Embedding: 768-dim vectors from Gemini text-embedding-004

-- ── 1. Enable pgvector ───────────────────────────────────────────────────────

create extension if not exists vector;

-- ── 2. Reference Library Table ───────────────────────────────────────────────

create table if not exists reference_library (
  id            uuid            primary key default gen_random_uuid(),
  user_id       uuid            not null references auth.users(id) on delete cascade,

  -- Source metadata
  source_url    text,                     -- original URL (YouTube, Instagram, Drive)
  source_type   text            not null  -- 'youtube' | 'instagram' | 'drive' | 'upload'
                check (source_type in ('youtube', 'instagram', 'drive', 'upload')),
  title         text,                     -- video/clip title from yt-dlp or user-provided

  -- Shot / clip metadata
  shot_id       text,                     -- internal shot ID (e.g. 'shot_001')
  start_sec     double precision,
  end_sec       double precision,
  duration      double precision,

  -- Frame / thumbnail
  frame_url     text,                     -- relative URL under /media/{project_id}/

  -- Intelligence fields
  description   text,                     -- Gemini vision description of the shot
  content_type  text,                     -- 'interview' | 'broll' | 'title_card' etc.

  -- Vector embedding for script matching
  -- Generated by Gemini text-embedding-004 (768-dim)
  embedding     vector(768),

  -- Timestamps
  created_at    timestamptz     not null default now(),
  updated_at    timestamptz     not null default now()
);

-- ── 3. Index for fast cosine similarity search ───────────────────────────────

-- IVFFlat: good for < 1M rows. Switch to HNSW for production scale.
create index if not exists reference_library_embedding_idx
  on reference_library
  using ivfflat (embedding vector_cosine_ops)
  with (lists = 100);

-- Standard indexes
create index if not exists reference_library_user_idx on reference_library (user_id);
create index if not exists reference_library_source_type_idx on reference_library (source_type);
create index if not exists reference_library_created_at_idx on reference_library (created_at desc);

-- ── 4. Row Level Security ─────────────────────────────────────────────────────

alter table reference_library enable row level security;

-- Users can only access their own library
create policy "Users can view their own library"
  on reference_library for select
  using (auth.uid() = user_id);

create policy "Users can insert into their own library"
  on reference_library for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own library clips"
  on reference_library for update
  using (auth.uid() = user_id);

create policy "Users can delete their own library clips"
  on reference_library for delete
  using (auth.uid() = user_id);

-- ── 5. Helper function: cosine similarity search ─────────────────────────────
-- Accepts a query embedding and returns top-k matches for a given user

create or replace function match_reference_library(
  query_embedding vector(768),
  match_user_id   uuid,
  match_count     int default 10
)
returns table (
  id            uuid,
  shot_id       text,
  title         text,
  source_url    text,
  source_type   text,
  frame_url     text,
  description   text,
  start_sec     double precision,
  end_sec       double precision,
  duration      double precision,
  similarity    float
)
language sql stable
as $$
  select
    rl.id,
    rl.shot_id,
    rl.title,
    rl.source_url,
    rl.source_type,
    rl.frame_url,
    rl.description,
    rl.start_sec,
    rl.end_sec,
    rl.duration,
    1 - (rl.embedding <=> query_embedding) as similarity
  from reference_library rl
  where rl.user_id = match_user_id
    and rl.embedding is not null
  order by rl.embedding <=> query_embedding
  limit match_count;
$$;
