import type { CarouselSlideItem } from '../types/assets';
import { getBrandKit } from './brandKit';

export interface CarouselTemplate {
  id: string;
  name: string;
  tagline: string;
  category: 'growth' | 'educational' | 'story' | 'framework';
  slideCount: number;
  badge: string;
  previewBg: string;
  createSlides: () => CarouselSlideItem[];
}

export function generateId(): string {
  return crypto.randomUUID();
}

/**
 * 8 Hand-Crafted Viral Carousel Templates
 */
export const CAROUSEL_TEMPLATES: CarouselTemplate[] = [
  {
    id: 'tool-roundup',
    name: 'Top 5 AI Stack',
    tagline: 'High-converting tool curation deck with rating pills and category badges',
    category: 'growth',
    slideCount: 4,
    badge: '🔥 Viral Format',
    previewBg: 'linear-gradient(135deg, #181b24 0%, #0c0d12 100%)',
    createSlides: () => {
      const brand = getBrandKit();
      return [
        {
          id: generateId(),
          backgroundColor: brand.backgroundColor || '#0C0D10',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'CURATED AI STACK 2026',
              x: 10,
              y: 20,
              fontSize: 16,
              fontWeight: 800,
              color: brand.primaryColor || '#4E6CF2',
              align: 'left',
              tag: 'tag',
            },
            {
              id: generateId(),
              content: '5 AI Tools That Will Save You 20+ Hours Every Week',
              x: 10,
              y: 35,
              fontSize: 48,
              fontWeight: 800,
              color: brand.textColor || '#ECECF0',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Tested by 1,400+ solo founders. Swipe to steal the stack →',
              x: 10,
              y: 75,
              fontSize: 22,
              fontWeight: 500,
              color: '#8A8F9E',
              align: 'left',
              tag: 'subtitle',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: brand.backgroundColor || '#0C0D10',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: '#01 · REVENUE AUTOMATION',
              x: 10,
              y: 18,
              fontSize: 15,
              fontWeight: 800,
              color: '#34D399',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: 'Atlas HQ (AI SDR)',
              x: 10,
              y: 30,
              fontSize: 42,
              fontWeight: 800,
              color: brand.textColor || '#ECECF0',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Scores Hacker News & YC founders against your ICP in real-time and drafts hyper-personalized LinkedIn DMs.',
              x: 10,
              y: 50,
              fontSize: 24,
              fontWeight: 400,
              color: '#A0A5B5',
              align: 'left',
              tag: 'body',
            },
            {
              id: generateId(),
              content: '⚡ ROI: 15 hrs saved/wk · $0 API setup',
              x: 10,
              y: 80,
              fontSize: 18,
              fontWeight: 700,
              color: brand.primaryColor || '#4E6CF2',
              align: 'left',
              tag: 'callout',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: brand.backgroundColor || '#0C0D10',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: '#02 · CONTENT DECONSTRUCTION',
              x: 10,
              y: 18,
              fontSize: 15,
              fontWeight: 800,
              color: '#FBBF24',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: 'Clario (Visual Remix)',
              x: 10,
              y: 30,
              fontSize: 42,
              fontWeight: 800,
              color: brand.textColor || '#ECECF0',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Extracts viral graphic blocks, icons and video hooks into reusable LEGO stickers that adapt to your brand palette.',
              x: 10,
              y: 50,
              fontSize: 24,
              fontWeight: 400,
              color: '#A0A5B5',
              align: 'left',
              tag: 'body',
            },
            {
              id: generateId(),
              content: '🎨 1-Click Brand Kit Apply · Instant Multi-Format Export',
              x: 10,
              y: 80,
              fontSize: 18,
              fontWeight: 700,
              color: '#FBBF24',
              align: 'left',
              tag: 'callout',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#0F121C',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'TAKEAWAY',
              x: 10,
              y: 20,
              fontSize: 16,
              fontWeight: 800,
              color: brand.accentColor || '#A5B4FC',
              align: 'left',
              tag: 'tag',
            },
            {
              id: generateId(),
              content: 'Automate Distribution. Focus on Product.',
              x: 10,
              y: 34,
              fontSize: 44,
              fontWeight: 800,
              color: brand.textColor || '#ECECF0',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Save this post for your next sprint.\nComment "STACK" and I will send you the Notion workflow guide.',
              x: 10,
              y: 60,
              fontSize: 24,
              fontWeight: 500,
              color: '#9CA3AF',
              align: 'left',
              tag: 'body',
            },
          ],
        },
      ];
    },
  },
  {
    id: 'before-after-case-study',
    name: 'Before vs After Breakdown',
    tagline: 'Split-comparison cards showcasing high-contrast transformation',
    category: 'framework',
    slideCount: 3,
    badge: '📈 Case Study',
    previewBg: 'linear-gradient(135deg, #1e1b4b 0%, #09090b 100%)',
    createSlides: () => {
      const brand = getBrandKit();
      return [
        {
          id: generateId(),
          backgroundColor: brand.backgroundColor || '#0C0D10',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'SYSTEMS OVER HAIL-MARYS',
              x: 10,
              y: 18,
              fontSize: 15,
              fontWeight: 800,
              color: '#F43F5E',
              align: 'left',
              tag: 'tag',
            },
            {
              id: generateId(),
              content: 'How We Scaled From $0 to $12k MRR Without a Sales Team',
              x: 10,
              y: 32,
              fontSize: 46,
              fontWeight: 800,
              color: brand.textColor || '#ECECF0',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'The exact breakdown of our outbound operating system.',
              x: 10,
              y: 72,
              fontSize: 22,
              fontWeight: 400,
              color: '#8A8F9E',
              align: 'left',
              tag: 'subtitle',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#0C0D10',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: '❌ BEFORE (MANUAL MESS)',
              x: 10,
              y: 18,
              fontSize: 18,
              fontWeight: 800,
              color: '#F43F5E',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: '• 4 hours/day hunting profiles manually\n• Generic cold copy getting 3% reply rate\n• Chaotic spreadsheets with lost follow-ups',
              x: 10,
              y: 28,
              fontSize: 22,
              fontWeight: 400,
              color: '#9CA3AF',
              align: 'left',
              tag: 'body',
            },
            {
              id: generateId(),
              content: '✅ AFTER (AUTONOMOUS MACHINE)',
              x: 10,
              y: 58,
              fontSize: 18,
              fontWeight: 800,
              color: '#10B981',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: '• Atlas HQ runs daily HN & YC scrape\n• ICP scoring filters only verified pain points\n• 38% reply rate with laser-focused founder thesis DMs',
              x: 10,
              y: 68,
              fontSize: 22,
              fontWeight: 400,
              color: '#E5E7EB',
              align: 'left',
              tag: 'body',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#0E1017',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'THE 3 CORE RULES',
              x: 10,
              y: 18,
              fontSize: 16,
              fontWeight: 800,
              color: brand.primaryColor || '#4E6CF2',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: '1. Never pitch in DM #1\n2. Quote their exact words\n3. Deliver the tool before asking for a call',
              x: 10,
              y: 34,
              fontSize: 28,
              fontWeight: 700,
              color: brand.textColor || '#ECECF0',
              align: 'left',
              tag: 'body',
            },
            {
              id: generateId(),
              content: 'Follow @pseudonyms for daily teardowns on building lean.',
              x: 10,
              y: 80,
              fontSize: 18,
              fontWeight: 600,
              color: brand.accentColor || '#A5B4FC',
              align: 'left',
              tag: 'callout',
            },
          ],
        },
      ];
    },
  },
  {
    id: 'step-framework',
    name: '3-Step Execution Framework',
    tagline: 'Clean numbered milestone progression for tutorials and SOPs',
    category: 'educational',
    slideCount: 4,
    badge: '📘 Educational',
    previewBg: 'linear-gradient(135deg, #064e3b 0%, #022c22 100%)',
    createSlides: () => {
      return [
        {
          id: generateId(),
          backgroundColor: '#06130E',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'ACTIONABLE FRAMEWORK',
              x: 10,
              y: 20,
              fontSize: 16,
              fontWeight: 800,
              color: '#34D399',
              align: 'left',
              tag: 'tag',
            },
            {
              id: generateId(),
              content: 'The 3-Step Engine to Turn 1 Video into 10 High-Reach Assets',
              x: 10,
              y: 35,
              fontSize: 46,
              fontWeight: 800,
              color: '#F9FAFB',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Stop making content from scratch every day. Do this instead.',
              x: 10,
              y: 75,
              fontSize: 22,
              fontWeight: 500,
              color: '#6EE7B7',
              align: 'left',
              tag: 'subtitle',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#06130E',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'STEP 01',
              x: 10,
              y: 18,
              fontSize: 16,
              fontWeight: 800,
              color: '#34D399',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: 'Extract the Core Hook',
              x: 10,
              y: 30,
              fontSize: 40,
              fontWeight: 800,
              color: '#FFFFFF',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Find the highest energy 3-second statement. Cut away all intros and pleasantries. Hook first, context later.',
              x: 10,
              y: 50,
              fontSize: 24,
              fontWeight: 400,
              color: '#A7F3D0',
              align: 'left',
              tag: 'body',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#06130E',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'STEP 02',
              x: 10,
              y: 18,
              fontSize: 16,
              fontWeight: 800,
              color: '#34D399',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: 'Deconstruct Into Visual LEGOs',
              x: 10,
              y: 30,
              fontSize: 38,
              fontWeight: 800,
              color: '#FFFFFF',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Isolate each stat callout and diagram into separate transparent PNG layers. Re-align them for vertical 9:16 and square 1:1 feeds.',
              x: 10,
              y: 50,
              fontSize: 24,
              fontWeight: 400,
              color: '#A7F3D0',
              align: 'left',
              tag: 'body',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#06130E',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'STEP 03',
              x: 10,
              y: 18,
              fontSize: 16,
              fontWeight: 800,
              color: '#34D399',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: 'Batch Publish Across 3 Channels',
              x: 10,
              y: 30,
              fontSize: 38,
              fontWeight: 800,
              color: '#FFFFFF',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: 'Export PDF carousel for LinkedIn, 9:16 video for Reels & Shorts, and single-card graphic for X/Twitter.',
              x: 10,
              y: 50,
              fontSize: 24,
              fontWeight: 400,
              color: '#A7F3D0',
              align: 'left',
              tag: 'body',
            },
          ],
        },
      ];
    },
  },
  {
    id: 'quote-authority',
    name: 'Bold Quote & Insight',
    tagline: 'High-contrast typography card for authority thought-leadership',
    category: 'story',
    slideCount: 2,
    badge: '💬 Authority',
    previewBg: 'linear-gradient(135deg, #311042 0%, #0e0514 100%)',
    createSlides: () => {
      const brand = getBrandKit();
      return [
        {
          id: generateId(),
          backgroundColor: '#0E0713',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: '“',
              x: 10,
              y: 12,
              fontSize: 96,
              fontWeight: 900,
              color: brand.primaryColor || '#818CF8',
              align: 'left',
              tag: 'tag',
            },
            {
              id: generateId(),
              content: 'The biggest mistake solo builders make is treating marketing as a phase after launch. Marketing is the conversation that shapes what you build.',
              x: 10,
              y: 36,
              fontSize: 36,
              fontWeight: 700,
              color: '#F3F4F6',
              align: 'left',
              tag: 'title',
            },
            {
              id: generateId(),
              content: '— Pseudonyms Blueprint on Cognitive Leverage',
              x: 10,
              y: 82,
              fontSize: 18,
              fontWeight: 600,
              color: '#C084FC',
              align: 'left',
              tag: 'subtitle',
            },
          ],
        },
        {
          id: generateId(),
          backgroundColor: '#0E0713',
          showBackdrop: true,
          width: 1080,
          height: 1080,
          elements: [],
          texts: [
            {
              id: generateId(),
              content: 'HOW TO APPLY THIS TODAY:',
              x: 10,
              y: 20,
              fontSize: 16,
              fontWeight: 800,
              color: '#C084FC',
              align: 'left',
              tag: 'step',
            },
            {
              id: generateId(),
              content: '1. Share your unfinished prototypes weekly\n2. Let user pushbacks write your changelog\n3. Build in public to build distribution first',
              x: 10,
              y: 36,
              fontSize: 26,
              fontWeight: 600,
              color: '#E9D5FF',
              align: 'left',
              tag: 'body',
            },
          ],
        },
      ];
    },
  },
];
