import { useState } from 'react';
import JSZip from 'jszip';
import { type HarvestProject, isProductionEligible } from '../types/assets';

interface ExportPhaseProps {
  project: HarvestProject;
  contactSheetUrl?: string;
  onBackToStudio: () => void;
  onStartOver: () => void;
}

export function ExportPhase({
  project,
  contactSheetUrl,
  onBackToStudio,
  onStartOver,
}: ExportPhaseProps) {
  const isVideo = project.mode === 'video_harvester';
  const [downloadingType, setDownloadingType] = useState<string | null>(null);
  const [activeReportTab, setActiveReportTab] = useState<
    'report_md' | 'manifest_csv' | 'prompts_md' | 'provenance_json'
  >('report_md');
  const [copiedTab, setCopiedTab] = useState<string | null>(null);
  const [showReferenceWarning, setShowReferenceWarning] = useState(false);

  // Strict data-layer filtering
  const allCleanAssets = project.clean_assets || [];
  const productionMasters = allCleanAssets.filter(c => isProductionEligible(c.rights_status));
  const unresolvedAttachments = allCleanAssets.filter(c => !isProductionEligible(c.rights_status));

  const allReplacements = project.replacements || [];
  const generatedOriginals = allReplacements.filter(r => r.replacement_type === 'generated_original');
  const reconstructedStills = allReplacements.filter(
    r => r.replacement_type === 'ai_cleaned_reference' || r.replacement_type === 'crop_reframe'
  );

  const refCount = isVideo ? project.shots.length : project.slides.length;
  const referenceSegments = project.reference_segments || [];
  const refSegCount = referenceSegments.length;
  const cleanEligibleCount = productionMasters.length;
  const unresolvedCount = unresolvedAttachments.length;
  const genCount = generatedOriginals.length;
  const reconCount = reconstructedStills.length;
  const productionPackTotal = cleanEligibleCount + genCount;

  const projectSlug = (project.name || 'project').replace(/[^a-zA-Z0-9_-]/g, '_');

  // 1. Generate Manifest CSV
  const generateShotManifestCsv = (): string => {
    if (!isVideo) {
      const headers = [
        'Slide_ID',
        'Slide_Index',
        'OCR_Transcript',
        'Headline_Font',
        'Dominant_Colors',
        'Layout_Archetype',
      ];
      const rows = project.slides.map(s => [
        s.slide_id,
        s.slide_index + 1,
        `"${(s.ocr_transcript || '').replace(/"/g, '""')}"`,
        `"${s.typography_tokens?.headlineFont || ''}"`,
        `"${(s.palette_tokens || []).join('; ')}"`,
        `"${s.layout_tokens?.archetype || ''}"`,
      ]);
      return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
    }

    const headers = [
      'Shot_ID',
      'Start_Sec',
      'End_Sec',
      'Duration_Sec',
      'Content_Type',
      'Source_Type',
      'Likely_Source',
      'Confidence',
      'Analysis_Confidence',
      'Resolution_Status',
      'Rights_Status',
      'Production_Eligible',
      'Editor_Text',
      'Source_Text',
      'Visual_Description',
      'Replacement_Prompt',
    ];
    const rows = project.shots.map(s => [
      s.shot_id,
      s.start_seconds,
      s.end_seconds,
      s.duration,
      s.content_type,
      s.source_type,
      `"${(s.likely_source || 'Unresolved').replace(/"/g, '""')}"`,
      s.confidence,
      s.analysis_confidence || 'low',
      s.resolution_status || 'needs_decision',
      s.rights_status || s.license_status,
      isProductionEligible(s.rights_status || s.license_status) ? 'YES' : 'NO',
      `"${(s.editor_text || '').replace(/"/g, '""')}"`,
      `"${(s.source_text || '').replace(/"/g, '""')}"`,
      `"${(s.visual_description || '').replace(/"/g, '""')}"`,
      `"${(s.replacement_prompt || '').replace(/"/g, '""')}"`,
    ]);
    return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
  };

  // 2. Generate Prompts Markdown
  const generatePromptsMd = (): string => {
    let md = `# Asset Prompts & Replacement Directives — ${project.name}\n\n`;
    md += `*Generated by Clario Asset Intelligence on ${new Date().toISOString()}*\n\n`;
    project.generated_prompts.forEach((p, idx) => {
      md += `### ${idx + 1}. ${p.title}\n`;
      md += `- **Target Model:** ${p.model_target.toUpperCase()}\n`;
      md += `- **Aspect Ratio:** ${p.aspect_ratio}\n`;
      md += `- **Intended Use:** ${p.intended_use}\n\n`;
      md += `\`\`\`text\n${p.prompt}\n\`\`\`\n\n`;
      if (p.negative_prompt) {
        md += `**Negative Prompt:** \`${p.negative_prompt}\`\n\n`;
      }
      md += `---\n\n`;
    });
    return md;
  };

  // 3. Generate Markdown Report
  const generateMarkdownReport = (isMixedArchive: boolean = false): string => {
    let md = `# Clario Asset Intelligence & Rights Report\n\n`;
    if (isMixedArchive) {
      md += `> [!WARNING]\n`;
      md += `> **MIXED-STATUS ARCHIVE:** This archive contains unverified reference materials, unresolved attachments, and research-only stills alongside production-eligible assets. Verify all licensing before commercial distribution.\n\n`;
    }
    md += `**Project:** ${project.name}\n`;
    md += `**Mode:** ${isVideo ? 'Video Harvester' : 'Slide & Carousel Harvester'}\n`;
    if (project.reference_url) md += `**Reference URL:** ${project.reference_url}\n`;
    md += `**Report Generated:** ${new Date().toISOString()}\n\n`;

    md += `## 1. Rights & Asset Inventory Breakdown\n`;
    md += `- **Production-Eligible Asset Masters:** ${cleanEligibleCount}\n`;
    md += `- **Generated Originals:** ${genCount}\n`;
    md += `- **Unresolved Attachments (Non-Production):** ${unresolvedCount}\n`;
    md += `- **Reconstructed Reference Stills (Research Only):** ${reconCount}\n`;
    md += `- **Reference Segments (Research Only):** ${refSegCount}\n`;
    md += `- **Reference Evidence Excerpts:** ${refCount}\n\n`;

    md += `## 2. Shot Intelligence & Clearance Status\n\n`;
    if (isVideo) {
      project.shots.forEach(s => {
        const eligible = isProductionEligible(s.rights_status || s.license_status);
        md += `### ${s.shot_id.toUpperCase()} (${s.start_seconds.toFixed(1)}s – ${s.end_seconds.toFixed(1)}s)\n`;
        md += `- **Description:** ${s.visual_description}\n`;
        md += `- **Likely Source:** ${s.likely_source} (Confidence: ${s.confidence})\n`;
        md += `- **Analysis Quality:** ${s.analysis_confidence ? s.analysis_confidence.toUpperCase() : 'LOW (FALLBACK)'}\n`;
        md += `- **Rights Status:** ${s.rights_status || s.license_status} (${eligible ? 'CLEARED FOR PRODUCTION' : 'EXCLUDED FROM PRODUCTION'})\n`;
        md += `- **Next Action:** ${s.next_action_label || 'Create original equivalent or attach clean master'}\n`;
        if (s.editor_text) md += `- **Burnt-in Captions:** "${s.editor_text}"\n`;
        if (s.source_text) md += `- **Scene Text:** "${s.source_text}"\n`;
        md += `\n`;
      });
    }
    return md;
  };

  // 4. Generate Provenance JSON
  const generateProvenanceJson = (): string => {
    const allRecords = [
      ...productionMasters.map(m => ({
        id: m.id || `${project.id}:${m.shot_id}`,
        project_id: project.id,
        project_name: project.name,
        shot_id: m.shot_id,
        asset_kind: 'attached_master',
        rights_status: m.rights_status || 'licensed_clean_source',
        production_eligible: true,
        title: m.title || `${m.shot_id.toUpperCase()} Master`,
        source_url: m.source_url || m.url,
        rights_note: m.rights_note || m.source_title || 'Verified Clean Master',
        lineage: m.transformation_history || ['User attached verified master'],
      })),
      ...unresolvedAttachments.map(u => ({
        id: u.id || `${project.id}:${u.shot_id}`,
        project_id: project.id,
        project_name: project.name,
        shot_id: u.shot_id,
        asset_kind: 'attached_master',
        rights_status: 'unresolved',
        production_eligible: false,
        title: u.title || `${u.shot_id.toUpperCase()} Attachment (Unresolved)`,
        source_url: u.source_url || u.url,
        rights_note: u.rights_note || 'Rights unresolved / unverified attachment. Excluded from production pack.',
        lineage: u.transformation_history || ['User attached file with unresolved rights status'],
      })),
      ...generatedOriginals.map(g => ({
        id: g.id || `${project.id}:${g.shot_id}`,
        project_id: project.id,
        project_name: project.name,
        shot_id: g.shot_id,
        asset_kind: 'generated_original',
        rights_status: 'generated_original',
        production_eligible: true,
        title: g.title || `${g.shot_id.toUpperCase()} Generated Original`,
        source_url: g.url,
        prompt: g.prompt,
        negative_prompt: g.negative_prompt,
        rights_note: g.rights_note || 'Generated functional original replacement',
        lineage: g.transformation_history || ['AI prompt synthesis for replacement original'],
      })),
      ...reconstructedStills.map(r => ({
        id: r.id || `${project.id}:${r.shot_id}`,
        project_id: project.id,
        project_name: project.name,
        shot_id: r.shot_id,
        asset_kind: 'reconstructed_still',
        rights_status: 'ai_cleaned_reference',
        production_eligible: false,
        title: r.title || `${r.shot_id.toUpperCase()} Reconstructed Still`,
        source_url: r.url,
        rights_note: 'Research-only reconstructed still. Not production-eligible.',
        lineage: r.transformation_history || ['Still inpainting reference for moodboard/research only'],
      })),
      ...(project.shots || []).map(s => ({
        id: `${project.id}:ref_${s.shot_id}`,
        project_id: project.id,
        project_name: project.name,
        shot_id: s.shot_id,
        asset_kind: 'reference_evidence',
        rights_status: 'reference_only',
        production_eligible: false,
        title: `${s.shot_id.toUpperCase()} Reference Frame`,
        source_url: s.clean_source_url || s.frame_url,
        rights_note: `Reference frame (${s.start_seconds.toFixed(1)}s - ${s.end_seconds.toFixed(1)}s). Not cleared for reuse.`,
        lineage: ['Extracted from reference video excerpt for visual analysis'],
      })),
      ...referenceSegments.map(rs => ({
        id: rs.id || `${project.id}:${rs.shot_id}_seg`,
        project_id: project.id,
        project_name: project.name,
        shot_id: rs.shot_id,
        asset_kind: 'reference_segment',
        rights_status: 'reference_only',
        production_eligible: false,
        title: rs.title || `${rs.shot_id.toUpperCase()} Reference Segment`,
        source_url: rs.url,
        rights_note: 'Reference segment. Not cleared for production.',
        lineage: ['Trimmed from reference video excerpt for visual analysis'],
      })),
    ];

    return JSON.stringify(
      {
        project_id: project.id,
        project_name: project.name,
        reference_url: project.reference_url,
        harvest_timestamp: project.created_at,
        shots_count: project.shots.length,
        production_eligible_count: cleanEligibleCount + genCount,
        unresolved_attachments_count: unresolvedCount,
        reconstructed_stills_count: reconCount,
        reference_segments_count: refSegCount,
        reference_evidence_count: refCount,
        assets: allRecords,
        provenance_records: project.provenance || [],
      },
      null,
      2
    );
  };

  // Direct Metadata File Download Helper
  const downloadMetadataFile = (filename: string, content: string, mimeType: string) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const handleDownloadMetadata = (type: 'report_md' | 'manifest_csv' | 'prompts_md' | 'provenance_json') => {
    switch (type) {
      case 'report_md':
        downloadMetadataFile(`CLARIO_REPORT_${projectSlug}.md`, generateMarkdownReport(), 'text/markdown');
        break;
      case 'manifest_csv':
        downloadMetadataFile(`SHOT_MANIFEST_${projectSlug}.csv`, generateShotManifestCsv(), 'text/csv');
        break;
      case 'prompts_md':
        downloadMetadataFile(`ASSET_PROMPTS_${projectSlug}.md`, generatePromptsMd(), 'text/markdown');
        break;
      case 'provenance_json':
        downloadMetadataFile(`PROVENANCE_MANIFEST_${projectSlug}.json`, generateProvenanceJson(), 'application/json');
        break;
    }
  };

  const getReportContent = () => {
    switch (activeReportTab) {
      case 'report_md':
        return generateMarkdownReport();
      case 'manifest_csv':
        return generateShotManifestCsv();
      case 'prompts_md':
        return generatePromptsMd();
      case 'provenance_json':
        return generateProvenanceJson();
    }
  };

  const handleCopyReport = () => {
    navigator.clipboard.writeText(getReportContent());
    setCopiedTab(activeReportTab);
    setTimeout(() => setCopiedTab(null), 1500);
  };

  // Export specific ZIP package with strict data filtering
  const handleExportPackage = async (
    type: 'production_pack' | 'prompts_only' | 'reconstructed_stills' | 'evidence_only' | 'mixed_archive'
  ) => {
    setDownloadingType(type);
    try {
      const zip = new JSZip();
      const folderName = `Clario_${projectSlug}`;
      const root = zip.folder(folderName) || zip;

      // Always include intelligence docs
      root.file('HARVEST_INTELLIGENCE_REPORT.md', generateMarkdownReport(type === 'mixed_archive'));
      root.file('SHOT_MANIFEST.csv', generateShotManifestCsv());
      root.file('ASSET_PROMPTS.md', generatePromptsMd());
      root.file('PROVENANCE_MANIFEST.json', generateProvenanceJson());

      // Helper to fetch blob
      const fetchBlob = async (url: string): Promise<Blob | null> => {
        try {
          const r = await fetch(url);
          return await r.blob();
        } catch {
          return null;
        }
      };

      // Strict Production Pack: ONLY productionMasters + generatedOriginals
      if (type === 'production_pack') {
        const cleanFolder = root.folder('01_production_eligible_masters');
        for (const a of productionMasters) {
          const b = await fetchBlob(a.url);
          if (b && cleanFolder) cleanFolder.file(`${a.shot_id}_clean_master.png`, b);
        }

        const repFolder = root.folder('02_generated_originals');
        for (const r of generatedOriginals) {
          const b = await fetchBlob(r.url);
          if (b && repFolder) repFolder.file(`${r.shot_id}_generated_original.jpg`, b);
        }
      }

      // Generated Prompts Only
      if (type === 'prompts_only') {
        const repFolder = root.folder('generated_originals');
        for (const r of generatedOriginals) {
          const b = await fetchBlob(r.url);
          if (b && repFolder) repFolder.file(`${r.shot_id}_generated_original.jpg`, b);
        }
      }

      // Reconstructed Research Stills Only
      if (type === 'reconstructed_stills') {
        const stillFolder = root.folder('reconstructed_reference_stills_research_only');
        for (const r of reconstructedStills) {
          const b = await fetchBlob(r.url);
          if (b && stillFolder) stillFolder.file(`${r.shot_id}_reconstructed_still.jpg`, b);
        }
      }

      // Reference Evidence Only
      if (type === 'evidence_only') {
        const refFolder = root.folder('reference_evidence_not_reusable');
        for (const s of project.shots) {
          if (s.frame_url) {
            const b = await fetchBlob(s.frame_url);
            if (b && refFolder) refFolder.file(`${s.shot_id}_ref_frame.jpg`, b);
          }
        }
        
        const refSegFolder = root.folder('reference_segments_not_reusable');
        for (const rs of referenceSegments) {
          if (rs.url) {
            const b = await fetchBlob(rs.url);
            if (b && refSegFolder) refSegFolder.file(rs.filename, b);
          }
        }
        
        if (contactSheetUrl) {
          const csBlob = await fetchBlob(contactSheetUrl);
          if (csBlob) root.file('REFERENCE_CONTACT_SHEET.jpg', csBlob);
        }
      }

      // Mixed Archive (Contains everything, explicitly labeled)
      if (type === 'mixed_archive') {
        root.file(
          'WARNING_MIXED_STATUS_ARCHIVE.txt',
          'NOTICE: This archive contains mixed-status assets including unverified reference extracts, unresolved attachments, and research stills. Verify all rights notes in PROVENANCE_MANIFEST.json before production reuse.'
        );

        const refFolder = root.folder('01_reference_evidence_not_reusable');
        for (const s of project.shots) {
          if (s.frame_url) {
            const b = await fetchBlob(s.frame_url);
            if (b && refFolder) refFolder.file(`${s.shot_id}_ref_frame.jpg`, b);
          }
        }
        if (contactSheetUrl) {
          const csBlob = await fetchBlob(contactSheetUrl);
          if (csBlob) root.file('REFERENCE_CONTACT_SHEET.jpg', csBlob);
        }

        if (productionMasters.length > 0) {
          const cleanFolder = root.folder('02_production_eligible_masters');
          for (const a of productionMasters) {
            const b = await fetchBlob(a.url);
            if (b && cleanFolder) cleanFolder.file(`${a.shot_id}_clean_master.png`, b);
          }
        }

        if (unresolvedAttachments.length > 0) {
          const unresFolder = root.folder('03_unresolved_attachments_not_cleared');
          for (const u of unresolvedAttachments) {
            const b = await fetchBlob(u.url);
            if (b && unresFolder) unresFolder.file(`${u.shot_id}_unresolved_attachment.png`, b);
          }
        }

        if (generatedOriginals.length > 0) {
          const repFolder = root.folder('04_generated_originals');
          for (const r of generatedOriginals) {
            const b = await fetchBlob(r.url);
            if (b && repFolder) repFolder.file(`${r.shot_id}_generated_original.jpg`, b);
          }
        }

        if (reconstructedStills.length > 0) {
          const stillFolder = root.folder('05_reconstructed_stills_research_only');
          for (const r of reconstructedStills) {
            const b = await fetchBlob(r.url);
            if (b && stillFolder) stillFolder.file(`${r.shot_id}_reconstructed_still.jpg`, b);
          }
        }
        
        if (referenceSegments.length > 0) {
          const segFolder = root.folder('06_reference_segments_not_cleared');
          for (const rs of referenceSegments) {
            const b = await fetchBlob(rs.url);
            if (b && segFolder) segFolder.file(rs.filename, b);
          }
        }
      }

      const zipBlob = await zip.generateAsync({ type: 'blob' });
      const downloadUrl = URL.createObjectURL(zipBlob);
      const a = document.createElement('a');
      a.href = downloadUrl;
      a.download = `clario_${projectSlug}_${type}.zip`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(downloadUrl);
    } catch (err) {
      console.error('ZIP generation error:', err);
    } finally {
      setDownloadingType(null);
    }
  };

  return (
    <div
      className="phase-enter"
      style={{
        flex: 1,
        background: 'var(--base)',
        color: 'var(--text-primary)',
        padding: '32px 32px 80px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        fontFamily: 'var(--font-sans)',
      }}
    >
      {/* Top Bar */}
      <div
        style={{
          width: '100%',
          maxWidth: 960,
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          marginBottom: 24,
        }}
      >
        <button
          onClick={onBackToStudio}
          className="btn-ghost"
          style={{ fontSize: 13, fontWeight: 600, color: 'var(--text-secondary)' }}
        >
          ← Back to Shot Queue
        </button>
        <button
          onClick={onStartOver}
          className="btn-ghost"
          style={{ fontSize: 13, color: 'var(--text-muted)' }}
        >
          Start New Harvest
        </button>
      </div>

      <div style={{ width: '100%', maxWidth: 960, display: 'flex', flexDirection: 'column', gap: 24 }}>
        {/* Header & Breakdown */}
        <div>
          <div
            style={{
              fontSize: 11,
              fontWeight: 700,
              letterSpacing: '0.08em',
              textTransform: 'uppercase',
              color: 'var(--accent)',
              marginBottom: 6,
            }}
          >
            Step 3 · Asset Distribution & Packaging
          </div>
          <h1
            style={{
              fontSize: 26,
              fontWeight: 800,
              fontFamily: 'var(--font-display)',
              letterSpacing: '-0.02em',
              marginBottom: 8,
              margin: 0,
            }}
          >
            Review & Export Pack
          </h1>
          <p style={{ fontSize: 13, color: 'var(--text-secondary)', margin: '6px 0 0', lineHeight: 1.5 }}>
            Clario enforces rights-strict packaging to separate production-eligible clean assets from research excerpts and unresolved attachments.
          </p>
        </div>

        {/* ── Asset Count Breakdown Card ────────────────────────────────────── */}
        <div
          className="paper-card"
          style={{
            padding: 20,
            display: 'grid',
            gridTemplateColumns: 'repeat(4, 1fr)',
            gap: 16,
            background: 'var(--panel)',
          }}
        >
          <div>
            <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: 'var(--emerald)', marginBottom: 4 }}>
              Production Masters
            </div>
            <div style={{ fontSize: 22, fontWeight: 800, fontFamily: 'var(--font-mono)', color: cleanEligibleCount > 0 ? 'var(--emerald)' : 'var(--text-primary)' }}>
              {cleanEligibleCount} <span style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-muted)' }}>assets</span>
            </div>
            <div style={{ fontSize: 11, color: 'var(--emerald)', marginTop: 2 }}>User-owned / licensed</div>
          </div>

          <div>
            <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: 'var(--accent)', marginBottom: 4 }}>
              Generated Originals
            </div>
            <div style={{ fontSize: 22, fontWeight: 800, fontFamily: 'var(--font-mono)', color: 'var(--accent)' }}>
              {genCount} <span style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-muted)' }}>prompts</span>
            </div>
            <div style={{ fontSize: 11, color: 'var(--accent)', marginTop: 2 }}>Rights-safe originals</div>
          </div>

          <div>
            <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: '#F59E0B', marginBottom: 4 }}>
              Unresolved / Research
            </div>
            <div style={{ fontSize: 22, fontWeight: 800, fontFamily: 'var(--font-mono)', color: '#F59E0B' }}>
              {unresolvedCount + reconCount} <span style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-muted)' }}>items</span>
            </div>
            <div style={{ fontSize: 11, color: '#F59E0B', marginTop: 2 }}>Non-production</div>
          </div>

          <div>
            <div style={{ fontSize: 10, fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-muted)', marginBottom: 4 }}>
              Reference Evidence
            </div>
            <div style={{ fontSize: 22, fontWeight: 800, fontFamily: 'var(--font-mono)' }}>
              {refCount} <span style={{ fontSize: 12, fontWeight: 500, color: 'var(--text-muted)' }}>frames</span>
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)', marginTop: 2 }}>Research excerpts</div>
          </div>
        </div>

        {/* ── Strict Rights Pre-Export Summary Box ──────────────────────────── */}
        <div
          style={{
            padding: '16px 20px',
            borderRadius: 10,
            background: 'var(--surface-2)',
            border: '1px solid var(--border)',
            display: 'flex',
            flexDirection: 'column',
            gap: 8,
          }}
        >
          <div style={{ fontSize: 12, fontWeight: 700, textTransform: 'uppercase', color: 'var(--text-primary)', display: 'flex', alignItems: 'center', gap: 6 }}>
            <span>🛡️ Production Pack Clearance Manifest</span>
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 8, fontSize: 12 }}>
            <div style={{ color: 'var(--emerald)' }}>
              ✓ <strong>{productionPackTotal}</strong> production-eligible assets included
            </div>
            <div style={{ color: unresolvedCount > 0 ? '#EF4444' : 'var(--text-muted)' }}>
              ⊘ <strong>{unresolvedCount}</strong> unresolved attachments excluded
            </div>
            <div style={{ color: 'var(--text-muted)' }}>
              ⊘ <strong>{refCount}</strong> reference frames excluded
            </div>
            <div style={{ color: 'var(--text-muted)' }}>
              ⊘ <strong>{reconCount}</strong> research stills excluded
            </div>
            <div style={{ color: 'var(--text-muted)' }}>
              ⊘ <strong>{refSegCount}</strong> reference segments excluded
            </div>
          </div>

          {unresolvedCount > 0 && (
            <div style={{ marginTop: 4, padding: '6px 10px', borderRadius: 6, background: 'rgba(239,68,68,0.08)', border: '1px solid rgba(239,68,68,0.25)', color: '#EF4444', fontSize: 11 }}>
              ⚠️ <strong>{unresolvedCount} unresolved attachment(s)</strong> are excluded from the strict production pack. Use the Mixed Archive if internal investigation files are required.
            </div>
          )}
        </div>

        {/* ── 4 Categorized Export Packages ─────────────────────────────────── */}
        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 16 }}>
          {/* Card 1: Strict Production Pack */}
          <div className="paper-card" style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
              <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>
                🛡️ Production Pack — Authorized & Generated Only
              </div>
              <span style={{ fontSize: 10, fontWeight: 700, padding: '2px 6px', borderRadius: 4, background: 'rgba(16,185,129,0.1)', color: 'var(--emerald)' }}>
                RECOMMENDED
              </span>
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.4 }}>
              Strict export containing only verified user-owned files, licensed clean masters, and generated originals. Excludes unresolved attachments and reference stills.
            </p>
            <button
              onClick={() => handleExportPackage('production_pack')}
              disabled={downloadingType !== null || productionPackTotal === 0}
              className="btn-primary"
              style={{
                marginTop: 'auto',
                padding: '11px 16px',
                fontSize: 12,
                background: productionPackTotal > 0 ? 'var(--emerald)' : 'var(--surface-2)',
                color: productionPackTotal > 0 ? '#FFFFFF' : 'var(--text-muted)',
                cursor: productionPackTotal > 0 ? 'pointer' : 'not-allowed',
                border: productionPackTotal > 0 ? 'none' : '1px solid var(--border)',
              }}
            >
              {productionPackTotal > 0
                ? `⬇ Export Production Pack (${productionPackTotal} Assets)`
                : 'No Production-Eligible Assets Attached'}
            </button>
          </div>

          {/* Card 2: Generated Originals & Prompts */}
          <div className="paper-card" style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>
              ✦ Generated Originals & Prompts (.ZIP)
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.4 }}>
              Prompt engineering pack with formatted Midjourney/Flux directives, style tokens, and negative prompts for AI production pipelines.
            </p>
            <button
              onClick={() => handleExportPackage('prompts_only')}
              disabled={downloadingType !== null}
              className="btn-ghost"
              style={{ marginTop: 'auto', padding: '11px 16px', fontSize: 12, border: '1px solid var(--border)' }}
            >
              ⬇ Export Generated Prompts Pack
            </button>
          </div>

          {/* Card 3: Reconstructed Reference Stills */}
          <div className="paper-card" style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>
              ⟡ Reconstructed Reference Stills — Research Only (.ZIP)
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.4 }}>
              Research stills for moodboards and pitch decks. Image stills only; does not restore continuous clean video.
            </p>
            <button
              onClick={() => handleExportPackage('reconstructed_stills')}
              disabled={downloadingType !== null || reconCount === 0}
              className="btn-ghost"
              style={{ marginTop: 'auto', padding: '11px 16px', fontSize: 12, border: '1px solid var(--border)' }}
            >
              {reconCount > 0 ? `⬇ Export Reconstructed Stills (${reconCount})` : 'No Stills Reconstructed'}
            </button>
          </div>

          {/* Card 4: Reference Evidence (with confirmation) */}
          <div className="paper-card" style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 10 }}>
            <div style={{ fontSize: 14, fontWeight: 700, color: 'var(--text-primary)' }}>
              🔍 Reference Evidence — Research Excerpts (.ZIP)
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.4 }}>
              Research archive of raw extracted video stills and OCR transcripts for internal review.
            </p>
            <button
              onClick={() => setShowReferenceWarning(true)}
              disabled={downloadingType !== null}
              className="btn-ghost"
              style={{ marginTop: 'auto', padding: '11px 16px', fontSize: 12, border: '1px solid var(--border)' }}
            >
              ⬇ Export Reference Evidence
            </button>
          </div>
        </div>

        {/* ── Complete Project Mixed Archive ─────────────────────────────────── */}
        <div
          className="paper-card"
          style={{
            padding: 18,
            background: 'var(--panel)',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            border: '1px dashed var(--border)',
          }}
        >
          <div>
            <div style={{ fontSize: 13, fontWeight: 700 }}>
              Complete Mixed Archive — Contains Unresolved & Research Materials
            </div>
            <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>
              Includes reference evidence, clean masters, prompt markdown, and JSON manifest. Filename: <code>clario_{projectSlug}_mixed_archive_unresolved.zip</code>
            </div>
          </div>
          <button
            onClick={() => handleExportPackage('mixed_archive')}
            disabled={downloadingType !== null}
            className="btn-ghost"
            style={{ padding: '8px 14px', fontSize: 11, border: '1px solid var(--border)' }}
          >
            {downloadingType === 'mixed_archive' ? 'Packaging…' : '⬇ Download Mixed Archive (.ZIP)'}
          </button>
        </div>

        {/* ── Reference Material Confirmation Alert ─────────────────────────── */}
        {showReferenceWarning && (
          <div
            style={{
              padding: 16,
              borderRadius: 8,
              background: 'rgba(239, 68, 68, 0.08)',
              border: '1px solid rgba(239, 68, 68, 0.3)',
              display: 'flex',
              flexDirection: 'column',
              gap: 10,
            }}
          >
            <div style={{ fontSize: 13, fontWeight: 700, color: '#EF4444' }}>
              ⚠️ Reference Material Notice
            </div>
            <p style={{ fontSize: 12, color: 'var(--text-secondary)', margin: 0, lineHeight: 1.4 }}>
              The Reference Evidence pack contains copyrighted frame stills extracted directly from third-party reference video. These files are not cleared for commercial reuse or redistribution.
            </p>
            <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end' }}>
              <button
                onClick={() => setShowReferenceWarning(false)}
                className="btn-ghost"
                style={{ padding: '6px 12px', fontSize: 11 }}
              >
                Cancel
              </button>
              <button
                onClick={() => {
                  setShowReferenceWarning(false);
                  handleExportPackage('evidence_only');
                }}
                className="btn-primary"
                style={{ padding: '6px 12px', fontSize: 11, background: '#EF4444', color: '#FFFFFF' }}
              >
                I Understand, Export Reference Evidence
              </button>
            </div>
          </div>
        )}

        {/* ── Real Metadata Downloads & Preview Section ──────────────────────── */}
        <div className="paper-card" style={{ padding: 20, display: 'flex', flexDirection: 'column', gap: 14 }}>
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', flexWrap: 'wrap', gap: 10 }}>
            <div>
              <div style={{ fontSize: 14, fontWeight: 700 }}>Structured Deliverables & Manifests</div>
              <div style={{ fontSize: 11, color: 'var(--text-muted)' }}>Click to download real metadata files or switch preview tabs below</div>
            </div>

            {/* Direct Download Buttons */}
            <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
              <button
                onClick={() => handleDownloadMetadata('report_md')}
                className="btn-primary"
                style={{ padding: '6px 10px', fontSize: 11 }}
              >
                ⬇ Report (.MD)
              </button>
              <button
                onClick={() => handleDownloadMetadata('manifest_csv')}
                className="btn-primary"
                style={{ padding: '6px 10px', fontSize: 11 }}
              >
                ⬇ Manifest (.CSV)
              </button>
              <button
                onClick={() => handleDownloadMetadata('prompts_md')}
                className="btn-primary"
                style={{ padding: '6px 10px', fontSize: 11 }}
              >
                ⬇ Prompts (.MD)
              </button>
              <button
                onClick={() => handleDownloadMetadata('provenance_json')}
                className="btn-primary"
                style={{ padding: '6px 10px', fontSize: 11 }}
              >
                ⬇ Provenance (.JSON)
              </button>
            </div>
          </div>

          {/* Preview Tab Selector */}
          <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', borderTop: '1px solid var(--border)', paddingTop: 12 }}>
            <div style={{ display: 'flex', gap: 6, background: 'var(--surface-2)', padding: 3, borderRadius: 8 }}>
              {[
                { id: 'report_md', label: 'Preview Report (.MD)' },
                { id: 'manifest_csv', label: 'Preview Manifest (.CSV)' },
                { id: 'prompts_md', label: 'Preview Prompts (.MD)' },
                { id: 'provenance_json', label: 'Preview Provenance (.JSON)' },
              ].map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveReportTab(tab.id as any)}
                  style={{
                    padding: '5px 10px',
                    borderRadius: 6,
                    fontSize: 11,
                    fontWeight: 600,
                    border: 'none',
                    background: activeReportTab === tab.id ? 'var(--panel)' : 'transparent',
                    color: activeReportTab === tab.id ? 'var(--text-primary)' : 'var(--text-secondary)',
                    cursor: 'pointer',
                  }}
                >
                  {tab.label}
                </button>
              ))}
            </div>

            <button
              onClick={handleCopyReport}
              className="btn-ghost"
              style={{ padding: '6px 12px', fontSize: 11, border: '1px solid var(--border)' }}
            >
              {copiedTab === activeReportTab ? '✓ Copied to Clipboard!' : '📋 Copy Preview Text'}
            </button>
          </div>

          <pre
            style={{
              padding: 16,
              background: 'var(--base)',
              border: '1px solid var(--border)',
              borderRadius: 8,
              fontSize: 11,
              fontFamily: 'var(--font-mono)',
              lineHeight: 1.5,
              maxHeight: 280,
              overflowY: 'auto',
              whiteSpace: 'pre-wrap',
              margin: 0,
              color: 'var(--text-secondary)',
            }}
          >
            {getReportContent()}
          </pre>
        </div>
      </div>
    </div>
  );
}
